###
GET http://localhost:4000/api/players

###
POST http://localhost:4000/api/players
Content-Type: application/json

{
    "name": "Edgar",
    "team": "Obregon"
}

###
GET http://localhost:4000/api/players/63a8172ffa35499a5aef7c99

###
DELETE http://localhost:4000/api/players/63a815153659ddecf815e262

###
PUT http://localhost:4000/api/players/63a8172ffa35499a5aef7c99
Content-Type: application/json

{
    "name": "Perla",
    "team": "Navojoa"
}